'''z = [15 , 8 , 9]
z[2] = 10

print(z)'''


'''z = [5 , 3 , 89 , 1001 , 7]
z[2] = 1000

print(z)
print(   z[2])'''


'''z = [7 , 6 , 9 , 5 , 3]

print(z)
print(z[0] + z[-1])'''


'''cheeses = ['parmesao' , 'mussarela' , 'gouda']
if 'mussarela' in cheeses:
    print('mussarela esta na lista')'''


'''z = [1 , 2 , 30 , 4 , 5]
if z[2] > 10:
    print ('maior do que dez')
else:
    print ('menor do que dez')'''


'''a = 0

if a == 0:
    c = 1000
    print(c)'''


'''z = [1 , 2 , 3 , 4 , 5]
for i in z:
    print (i)'''

